bool
BreakBeforeBinaryOperators(bool someVeryVeryLongConditionThatBarelyFitsOnALine, bool someOtherLongishConditionPart1, bool someOtherEvenLongerNestedConditionPart2)
{
	return someVeryVeryLongConditionThatBarelyFitsOnALine && (someOtherLongishConditionPart1 || someOtherEvenLongerNestedConditionPart2);
}
